#!/usr/bin/env python3
"""
Main function description - To show in command help
"""
import sys
import argparse
import logging

from o3skim import sources, utils


def cmdline_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    # Arguments
    p.add_argument("-f", "--sources_file", type=str, default="./sources.yaml",
                   help="custom sources YAML configuration (default: %(default)s)")
    p.add_argument("-v", "--verbosity", type=str, default='ERROR',
                   choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'], 
                   help="Sets the logging level (default: %(default)s)")
    return(p.parse_args())


if __name__ == '__main__':
    args = cmdline_args()

    # Set logging level
    logging.basicConfig(level=getattr(logging, args.verbosity))

    # Configuration load
    config = utils.load(args.sources_file) 
    logging.info("Configuration found at: %s", args.sources_file)
    logging.debug("Configuration info: %s", config)

    # Create sources
    logging.info("Loading data from './data' ")
    with utils.cd("data"):
        ds = {name: sources.Source(name, collection) for
              name, collection in config.items()}
    logging.debug("Sources loaded: %s", [k for k in config.keys()])

    # Skim output
    logging.info("Skimming data to './output' ")
    with utils.cd("output"):
        [source.skim() for source in ds.values()] 

