#!/usr/bin/env python3
"""
Main function description - To show in command help
"""
import sys
import argparse
import logging

from o3skim import sources


def cmdline_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    # Arguments
    p.add_argument("-f", "--sources_file", type=str, default="./sources.yaml",
                   help="custom sources YAML configuration (default: %(default)s)")
    p.add_argument("-v", "--verbosity", type=str, default='ERROR',
                   choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'], 
                   help="Sets the logging level (default: %(default)s)")
    return(p.parse_args())


if __name__ == '__main__':
    args = cmdline_args()

    # Set logging level
    logging.basicConfig(level=getattr(logging, args.verbosity))

    # Configuration load
    config = sources.load(args.sources_file) 
    logging.info(config)

