config:
  project_repos:
    o3skim:
      repo: 'https://codebase.helmholtz.cloud/m-team/o3as/o3skim.git'
      branch: main 

sqa_criteria:
  qc_style:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
              - qc.uni
  qc_security:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - qc.sec
  qc_doc:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - qc.doc

#environment:
#  LANG: C.UTF-8

timeout: 900
