config:
  project_repos:
    o3skim:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3skim.git'
      branch: main 

sqa_criteria:
  QC.Sty:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - qc.sty
  QC.Uni:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
              - qc.uni
  QC.Sec:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - qc.sec
  QC.Doc:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - qc.doc

#environment:
#  LANG: C.UTF-8

timeout: 900
