version: "3.6"

services:
  testing:
    image: "indigodatacloud/ci-images:python3.6"
    container_name: "testing"
    volumes:
      - type: bind
        source: ./o3skim
        target: /o3skim

  o3skim:
     build:
        context: "."
        dockerfile: "./o3skim/Dockerfile"
     image: "o3as/o3skim:test"