"""
O3as package with classes and utilities to handle ozone data skimming.

The main usage of the package resides on the generation of "Source"
class instances from the loading of netCDF files though collection 
descriptions generated by source files.

However, as the generation of collection descriptions in a form of dict
type might be difficult, a yaml file can be converted into the required
variable by using the util "load" with the path to the 'sources.yaml'
file as input.

Once the desired collection is formated in the shape of dict variable,
a source object can be created from using the class "Source". During 
this step the model data is loaded into the source instance involving 
on the background process the data sorting and standardization. Note 
that those models with errors on the collection specification are not 
loaded neither interrupt the loading process. However, notice of those
event is logged on strerr together with the stack execution info.

After the data has been loaded the object intstance correctly created,
it is possible to use the internal methods to generate a reduced output
on the current folder.

To simplify the management of the data and output directories, the 
package offest a "cd" utility which can be used together with a "with"
statement to change temporary the location of the execution folder. 
"""

from o3skim import extended_xarray
from o3skim import source
from o3skim import standardization
from o3skim import utils

Source = source.Source
load = utils.load
cd = utils.cd
